### ISSUE TITLE
Орфографические и пунктуационные ошибки

### ISSUE THREAD

**Issue by danik28** [savushkin-r-d/PLCnext-howto#41]
Слово "auto-suggested", должно писаться с предлогом "the".
После слова "thus", должна стоять запятая.

Ссылка на документ с ошибками:
 https://github.com/savushkin-r-d/PLCnext-howto/tree/master/HowTo%20build%20program%20Hello%20PLCnext

**Comment by idzm** [comment]
Необходимо создать запрос (**pull request**) и предложить исправления данных ошибок.
